service: <service-name>
frameworkVersion: '3'
provider:
    name: aws
    region: <your-region>
    runtime: <your-runtime>

# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml#functions
functions:
    createLoyaltyCardFunction:
        name: createLoyaltyCard
        role: arn:aws:iam::<account-id>:role/<lambda-execution-role-name>
        handler: handler.create_loyalty_card
        events:
        - http:
            path: <your-api-path>
            method: <your-method>

    # TODO

package:
    exclude:
        - venv/**
        - node_modules/**
resources:
    Resources:
        LoyaltyCardDynamodbTable:
            Type: AWS::DynamoDB::Table
            Properties:
                AttributeDefinitions:
                - AttributeName: <attribute-name>
                  AttributeType: <attribute-type>
                KeySchema:
                - AttributeName: <attribute-name>
                  KeyType: HASH
                BillingMode: <billing-mode>
                TableName: <your-table-name>